ThongKe/Controllers/BaoCaoController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using ThongKe.Data.Repository;
using ThongKe.Models;

namespace ThongKe.Controllers
{
    public class BaoCaoController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BaoCaoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SaleTheoQuay(string tungay = null, string denngay = null, string chiNhanh = null, string khoi = null)
        {
            var dtSaleQuayVM = new DoanhthuSaleQuayViewModel();

            var chiNhanhs = _unitOfWork.chiNhanhRepository.GetAll().Select(x => x.Chinhanh1).Distinct().ToArray();

            for (int i = 0; i < chiNhanhs.Count(); i++)
            {
                var cnToreturn = new ChiNhanhToReturnViewModel()
                {
                    Stt = i,
                    Name = chiNhanhs[i]
                };

                dtSaleQuayVM.chiNhanhToReturnViewModels.Add(cnToreturn);
            }

            try
            {
                ViewBag.searchFromDate = tungay;
                ViewBag.searchToDate = denngay;
                chiNhanh = chiNhanh ?? "";
                ViewBag.chiNhanh = chiNhanh;


                if (tungay == null || denngay == null)
                {
                    return View("SaleTheoQuay", dtSaleQuayVM);
                }

                var list = _unitOfWork.thongKeRepository.listSaleTheoQuay(tungay, denngay, chiNhanh, khoi);
                dtSaleQuayVM.DoanhthuSaleQuays = list;
                return View(dtSaleQuayVM);
            }
            catch
            {
                SetAlert("Lỗi định dạng ngày tháng", "error");
                return View("SaleTheoQuay", dtSaleQuayVM);
            }

        }

        [HttpPost]
        public IActionResult SaleTheoQuayPost(string tungay, string denngay, string chinhanh, string khoi)//(string tungay,string denngay, string daily)
        {
            if (tungay == null || denngay == null)
            {
                return RedirectToAction("SaleTheoQuay");
            }
            try
            {
                DateTime.Parse(tungay);
                DateTime.Parse(denngay);
            }
            catch
            {
                SetAlert("Lỗi định dạng ngày tháng", "error");
                return RedirectToAction("SaleTheoQuay");
            }
            //chinhanh = String.IsNullOrEmpty(chinhanh) ? Session["chinhanh"].ToString() : chinhanh;
            //khoi = String.IsNullOrEmpty(khoi) ? Session["khoi"].ToString() : khoi;

            chinhanh = chinhanh ?? "";
            string fromTo = "";
            ExcelPackage ExcelApp = new ExcelPackage();
            ExcelWorksheet xlSheet = ExcelApp.Workbook.Worksheets.Add("Report");
            // Định dạng chiều dài cho cột
            xlSheet.Column(1).Width = 10;//stt
            xlSheet.Column(2).Width = 50;// sales
            xlSheet.Column(3).Width = 10;//stt
            xlSheet.Column(4).Width = 30;// doanh so
            xlSheet.Column(5).Width = 30;// doanh thu sale

            xlSheet.Cells[2, 1].Value = "BÁO CÁO DOANH THU THEO NGÀY BÁN QUẦY " + khoi + " " + chinhanh;
            xlSheet.Cells[2, 1].Style.Font.SetFromFont(new Font("Times New Roman", 16, FontStyle.Bold));
            xlSheet.Cells[2, 1, 2, 5].Merge = true;
            setCenterAligment(2, 1, 2, 5, xlSheet);
            // dinh dang tu ngay den ngay
            if (tungay == denngay)
            {
                fromTo = "Ngày: " + tungay;
            }
            else
            {
                fromTo = "Từ ngày: " + tungay + " đến ngày: " + denngay;
            }
            xlSheet.Cells[3, 1].Value = fromTo;
            xlSheet.Cells[3, 1, 3, 5].Merge = true;
            xlSheet.Cells[3, 1].Style.Font.SetFromFont(new Font("Times New Roman", 14, FontStyle.Bold));
            setCenterAligment(3, 1, 3, 5, xlSheet);

            // Tạo header
            xlSheet.Cells[5, 1].Value = "STT";
            xlSheet.Cells[5, 2].Value = "Nhân viên ";
            xlSheet.Cells[5, 3].Value = "Code chinhanh ";

            xlSheet.Cells[5, 4].Value = "Tổng tiền";
            xlSheet.Cells[5, 5].Value = "Doanh số";

            xlSheet.Cells[5, 1, 5, 5].Style.Font.SetFromFont(new Font("Times New Roman", 12, FontStyle.Bold));

            // do du lieu tu table  
            int dong = 5;


            var d = _unitOfWork.thongKeRepository.listSaleTheoQuay(tungay, denngay, chinhanh, khoi);// Session["daily"].ToString(), Session["khoi"].ToString());

            //du lieu
            int iRowIndex = 6;
            int idem = 1;

            if (d != null)
            {
                foreach (var vm in d)
                {
                    xlSheet.Cells[iRowIndex, 1].Value = idem;
                    TrSetCellBorder(xlSheet, iRowIndex, 1, ExcelBorderStyle.Dotted, ExcelHorizontalAlignment.Center, Color.Silver, "Times New Roman", 10, FontStyle.Regular);
                    xlSheet.Cells[iRowIndex, 1].Style.Border.Right.Style = ExcelBorderStyle.Thin;

                    xlSheet.Cells[iRowIndex, 2].Value = vm.Nguoixuatve;
                    TrSetCellBorder(xlSheet, iRowIndex, 2, ExcelBorderStyle.Dotted, ExcelHorizontalAlignment.Left, Color.Silver, "Times New Roman", 10, FontStyle.Regular);
                    xlSheet.Cells[iRowIndex, 2].Style.Border.Right.Style = ExcelBorderStyle.Thin;

                    xlSheet.Cells[iRowIndex, 3].Value = vm.Chinhanh;
                    TrSetCellBorder(xlSheet, iRowIndex, 3, ExcelBorderStyle.Dotted, ExcelHorizontalAlignment.Center, Color.Silver, "Times New Roman", 10, FontStyle.Regular);
                    xlSheet.Cells[iRowIndex, 3].Style.Border.Right.Style = ExcelBorderStyle.Thin;

                    xlSheet.Cells[iRowIndex, 4].Value = vm.Doanhso;
                    TrSetCellBorder(xlSheet, iRowIndex, 4, ExcelBorderStyle.Dotted, ExcelHorizontalAlignment.Right, Color.Silver, "Times New Roman", 10, FontStyle.Regular);
                    xlSheet.Cells[iRowIndex, 4].Style.Border.Right.Style = ExcelBorderStyle.Thin;

                    xlSheet.Cells[iRowIndex, 5].Value = vm.Thucthu;
                    TrSetCellBorder(xlSheet, iRowIndex, 4, ExcelBorderStyle.Dotted, ExcelHorizontalAlignment.Right, Color.Silver, "Times New Roman", 10, FontStyle.Regular);
                    xlSheet.Cells[iRowIndex, 5].Style.Border.Right.Style = ExcelBorderStyle.Thin;


                    iRowIndex += 1;
                    idem += 1;
                    dong++;
                }
            }
            else
            {
                SetAlert("No sale.", "warning");
                return RedirectToAction(nameof(SaleTheoQuay));
            }

            dong++;
            //// Merger cot 4,5 ghi tổng tiền
            //setRightAligment(dong, 3, dong, 3, xlSheet);
            //xlSheet.Cells[dong, 1, dong, 2].Merge = true;
            //xlSheet.Cells[dong, 1].Value = "Tổng tiền: ";
            // Sum tổng tiền
            xlSheet.Cells[dong, 4].Formula = "SUM(D6:D" + (6 + d.Count() - 1) + ")";
            xlSheet.Cells[dong, 5].Formula = "SUM(E6:E" + (6 + d.Count() - 1) + ")";


            setBorder(5, 1, 5 + d.Count(), 5, xlSheet);
            setFontBold(5, 1, 5, 5, 11, xlSheet);
            setFontSize(6, 1, 6 + d.Count(), 5, 11, xlSheet);
            // canh giua cot stt
            setCenterAligment(6, 1, 6 + d.Count(), 1, xlSheet);
            // canh giua code chinhanh
            setCenterAligment(6, 3, 6 + d.Count(), 3, xlSheet);
            NumberFormat(6, 4, 6 + d.Count(), 5, xlSheet);
            // định dạng số cot tong cong
            NumberFormat(dong, 4, dong, 5, xlSheet);
            setBorder(dong, 4, dong, 5, xlSheet);
            setFontBold(dong, 4, dong, 5, 12, xlSheet);

            //xlSheet.View.FreezePanes(6, 20);

            //end du lieu

            byte[] fileContents;
            fileContents = ExcelApp.GetAsByteArray();

            if (fileContents == null || fileContents.Length == 0)
            {
                return NotFound();
            }
            string sFilename = "DoanhThuSale_" + khoi + " " + chinhanh + "_" + System.DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + ".xlsx";

            return File(
                fileContents: fileContents,
                contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                fileDownloadName: sFilename
            );
        }

        public IActionResult SaleTheoQuayChiTietToExcel(string tungay, string denngay, string nhanvien, string chinhanh, string khoi)
        {
            try
            {
                nhanvien = convertToUnSign3(nhanvien);
                //khoi = String.IsNullOrEmpty(khoi) ? Session["khoi"].ToString() : khoi;
                string fromTo = "";
                ExcelPackage ExcelApp = new ExcelPackage();
                ExcelWorksheet xlSheet = ExcelApp.Workbook.Worksheets.Add("DoanhthuSale");
                // Định dạng chiều dài cho cột
                xlSheet.Column(1).Width = 10;//stt
                xlSheet.Column(2).Width = 10;// chi nhanh
                xlSheet.Column(3).Width = 25;// code
                xlSheet.Column(4).Width = 25;// tuyen tham quan
                xlSheet.Column(5).Width = 40;// ten khach
                xlSheet.Column(6).Width = 10;// so khach
                xlSheet.Column(7).Width = 20;//doanhthu
                xlSheet.Column(8).Width = 20;//thuc thu
                xlSheet.Column(9).Width = 35;//sales

                xlSheet.Cells[2, 1].Value = "BÁO CÁO DOANH THU THEO NGÀY BÁN SALE " + nhanvien;

ThongKe/Views/Shared/_Layout.cshtml
@*@inject SignInManager<ApplicationUser> signInManager;*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"]</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/lib/dist/css/adminlte.min.css">*@
    <link href="~/lib/dist/css/adminlte.min.css" rel="stylesheet" />
    <link href="~/lib/jqueryui/jquery-ui.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini text-sm sidebar-open" style="height: auto;">

    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->

        <nav class="main-header navbar navbar-expand navbar-dark navbar-gray-dark">

            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
                @*<li class="nav-item d-none d-sm-inline-block">
                        <a asp-action="Register" asp-controller="Accounts" class="nav-link">Register</a>
                    </li>*@
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            @*<form class="form-inline ml-3">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>*@

            <!-- Right navbar links -->

            <partial name="_LoginPartial.cshtml" />


        </nav>

        <!-- /.navbar -->
        <!-- Main Sidebar Container -->

        <partial name="_Leftmenu.cshtml" />

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @if (TempData["AlertMessage"] != null)
            {
                <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                    @TempData["AlertMessage"]
                </div>
            }

            @RenderBody()
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.0.0-rc.3
            </div>
            <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
            reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    @*<script src="~/lib/plugins/jquery/jquery.min.js"></script>*@
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.js"></script>
    @*<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script src="~/lib/jquery.maskedinput/jquery.maskedinput.js"></script>
    <script src="~/lib/bootbox.js/bootbox.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/lib/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.js"></script>
    <!-- DataTables -->
    <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.js"></script>
    <!-- AdminLTE App -->
    <script src="~/lib/dist/js/adminlte.js"></script>

    @RenderSection("Scripts", required: false)
    <script>
        $(function () {
            $(".maskInput").mask("99/99/9999");

            $('#AlertBox').removeClass('hide');
            $('#AlertBox').delay(1000).slideUp(1000);
        });

    </script>
    <style>
        .error {
            color: red;
        }
    </style>
</body>
</html>

ThongKe/Views/Shared/_Leftmenu.cshtml
@*@inject SignInManager<ApplicationUser> signInManager*@

<aside class="main-sidebar sidebar-dark-navy elevation-4">

    <!-- Brand Logo -->
    <a href="~/lib/index3.html" class="brand-link">
        <img src="~/lib/dist/img/AdminLTELogo.png"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/lib/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Alexander Pierce</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Tài khoản

                        </p>
                    </a>

                </li>
                @* Danh muc báo cáo *@
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Báo cáo Doanh Thu
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="BaoCao" asp-action="SaleTheoQuay" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Sale theo ngày bán</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="BaoCao" asp-action="SaleTheoNgayDi" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Sale theo ngày đi tour</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="BaoCao" asp-action="SaleTheoTuyenThamQuan" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Sale theo tuyến tham quan</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="BaoCao" asp-action="QuayTheoNgayBan" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Quầy theo ngày bán</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="LoaiPhanMems" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Quầy theo ngày đi tour</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="LoaiPhanMems" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Đoàn Theo Ngày đi tour</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="LoaiPhanMems" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Tuyến tham quan theo ngày đi tour</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="LoaiPhanMems" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Tuyến tham quan theo quý</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="LoaiPhanMems" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Quầy khách lẽ toàn hệ thống</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Kinh doanh Online
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="ThietBis" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Theo ngày bán</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="LoaiThietBis" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Theo ngày đi</p>
                            </a>
                        </li>

                    </ul>
                </li>


            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>